# Generated by Django 6.0.3 on 2026-05-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=12, verbose_name='rol'),
        ),
    ]
